#!/usr/bin/env python3
"""Build airlines.json and airports.json for ADS-B enrichment.

Airlines: ICAO 3-letter code -> name, country, callsign
Airports: ICAO 4-letter code -> name, city, country, iata, lat, lon

Sources are embedded — no download needed.
"""
import json
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "payloads", "sdr", "data")

AIRLINES = {
    "AAL": {"name": "American Airlines", "country": "United States", "callsign": "AMERICAN"},
    "AAR": {"name": "Asiana Airlines", "country": "South Korea", "callsign": "ASIANA"},
    "ACA": {"name": "Air Canada", "country": "Canada", "callsign": "AIR CANADA"},
    "AEA": {"name": "Air Europa", "country": "Spain", "callsign": "EUROPA"},
    "AEE": {"name": "Aegean Airlines", "country": "Greece", "callsign": "AEGEAN"},
    "AFL": {"name": "Aeroflot", "country": "Russia", "callsign": "AEROFLOT"},
    "AFR": {"name": "Air France", "country": "France", "callsign": "AIRFRANS"},
    "AIC": {"name": "Air India", "country": "India", "callsign": "AIRINDIA"},
    "AIB": {"name": "Airbus Industrie", "country": "France", "callsign": "AIRBUS"},
    "ANA": {"name": "All Nippon Airways", "country": "Japan", "callsign": "ALL NIPPON"},
    "ANZ": {"name": "Air New Zealand", "country": "New Zealand", "callsign": "NEW ZEALAND"},
    "ASA": {"name": "Alaska Airlines", "country": "United States", "callsign": "ALASKA"},
    "AUA": {"name": "Austrian Airlines", "country": "Austria", "callsign": "AUSTRIAN"},
    "AUI": {"name": "Ukraine Intl Airlines", "country": "Ukraine", "callsign": "UKRAINE INTL"},
    "AVA": {"name": "Avianca", "country": "Colombia", "callsign": "AVIANCA"},
    "AZA": {"name": "ITA Airways", "country": "Italy", "callsign": "ITARLINES"},
    "BAW": {"name": "British Airways", "country": "United Kingdom", "callsign": "SPEEDBIRD"},
    "BEE": {"name": "Flybe", "country": "United Kingdom", "callsign": "JERSEY"},
    "BEL": {"name": "Brussels Airlines", "country": "Belgium", "callsign": "BEE-LINE"},
    "BER": {"name": "Air Berlin", "country": "Germany", "callsign": "AIR BERLIN"},
    "BLA": {"name": "Blue Air", "country": "Romania", "callsign": "BLUE AIR"},
    "BMS": {"name": "Bristol Helicopters", "country": "United Kingdom", "callsign": "DOVETAIL"},
    "BPA": {"name": "Blue Panorama Airlines", "country": "Italy", "callsign": "BLUE PANORAMA"},
    "CAL": {"name": "China Airlines", "country": "Taiwan", "callsign": "DYNASTY"},
    "CCA": {"name": "Air China", "country": "China", "callsign": "AIR CHINA"},
    "CES": {"name": "China Eastern Airlines", "country": "China", "callsign": "CHINA EASTERN"},
    "CFG": {"name": "Condor", "country": "Germany", "callsign": "CONDOR"},
    "CLH": {"name": "Lufthansa CityLine", "country": "Germany", "callsign": "HANSALINE"},
    "CPA": {"name": "Cathay Pacific", "country": "Hong Kong", "callsign": "CATHAY"},
    "CSN": {"name": "China Southern Airlines", "country": "China", "callsign": "CHINA SOUTHERN"},
    "CTN": {"name": "Croatia Airlines", "country": "Croatia", "callsign": "CROATIA"},
    "CXA": {"name": "Xiamen Airlines", "country": "China", "callsign": "XIAMEN AIR"},
    "DAL": {"name": "Delta Air Lines", "country": "United States", "callsign": "DELTA"},
    "DLH": {"name": "Lufthansa", "country": "Germany", "callsign": "LUFTHANSA"},
    "EIN": {"name": "Aer Lingus", "country": "Ireland", "callsign": "SHAMROCK"},
    "EJU": {"name": "easyJet Europe", "country": "Austria", "callsign": "ALPINE"},
    "ETD": {"name": "Etihad Airways", "country": "United Arab Emirates", "callsign": "ETIHAD"},
    "ETH": {"name": "Ethiopian Airlines", "country": "Ethiopia", "callsign": "ETHIOPIAN"},
    "EVA": {"name": "EVA Air", "country": "Taiwan", "callsign": "EVA"},
    "EWG": {"name": "Eurowings", "country": "Germany", "callsign": "EUROWINGS"},
    "EZS": {"name": "easyJet Switzerland", "country": "Switzerland", "callsign": "TOPSWISS"},
    "EZY": {"name": "easyJet", "country": "United Kingdom", "callsign": "EASY"},
    "FDX": {"name": "FedEx Express", "country": "United States", "callsign": "FEDEX"},
    "FIN": {"name": "Finnair", "country": "Finland", "callsign": "FINNAIR"},
    "FPO": {"name": "ASL Airlines France", "country": "France", "callsign": "FRENCH POST"},
    "GAF": {"name": "German Air Force", "country": "Germany", "callsign": "GERMAN AIR FORCE"},
    "GEC": {"name": "Lufthansa Cargo", "country": "Germany", "callsign": "LUFTHANSA CARGO"},
    "GIA": {"name": "Garuda Indonesia", "country": "Indonesia", "callsign": "INDONESIA"},
    "GTI": {"name": "Atlas Air", "country": "United States", "callsign": "GIANT"},
    "GWI": {"name": "Germanwings", "country": "Germany", "callsign": "GERMAN WINGS"},
    "HAL": {"name": "Hawaiian Airlines", "country": "United States", "callsign": "HAWAIIAN"},
    "HFM": {"name": "iFly", "country": "France", "callsign": "IFLY"},
    "IBE": {"name": "Iberia", "country": "Spain", "callsign": "IBERIA"},
    "IBK": {"name": "Norwegian Air Int'l", "country": "Ireland", "callsign": "NORTRANS"},
    "ICE": {"name": "Icelandair", "country": "Iceland", "callsign": "ICEAIR"},
    "IRA": {"name": "Iran Air", "country": "Iran", "callsign": "IRANAIR"},
    "JAL": {"name": "Japan Airlines", "country": "Japan", "callsign": "JAPAN AIR"},
    "JBU": {"name": "JetBlue Airways", "country": "United States", "callsign": "JETBLUE"},
    "KAL": {"name": "Korean Air", "country": "South Korea", "callsign": "KOREANAIR"},
    "KLM": {"name": "KLM Royal Dutch", "country": "Netherlands", "callsign": "KLM"},
    "KQA": {"name": "Kenya Airways", "country": "Kenya", "callsign": "KENYA"},
    "LAN": {"name": "LATAM Chile", "country": "Chile", "callsign": "LAN"},
    "LOT": {"name": "LOT Polish Airlines", "country": "Poland", "callsign": "LOT"},
    "MAH": {"name": "Malev Hungarian", "country": "Hungary", "callsign": "MALEV"},
    "MAS": {"name": "Malaysia Airlines", "country": "Malaysia", "callsign": "MALAYSIAN"},
    "MAU": {"name": "Air Mauritius", "country": "Mauritius", "callsign": "AIRMAURITIUS"},
    "MSR": {"name": "EgyptAir", "country": "Egypt", "callsign": "EGYPTAIR"},
    "NAX": {"name": "Norwegian Air Shuttle", "country": "Norway", "callsign": "NORSHUTTLE"},
    "NKS": {"name": "Spirit Airlines", "country": "United States", "callsign": "SPIRIT WINGS"},
    "OAL": {"name": "Olympic Air", "country": "Greece", "callsign": "OLYMPIC"},
    "PAC": {"name": "Polar Air Cargo", "country": "United States", "callsign": "POLAR"},
    "PGT": {"name": "Pegasus Airlines", "country": "Turkey", "callsign": "SUNTURK"},
    "PIA": {"name": "Pakistan Intl Airlines", "country": "Pakistan", "callsign": "PAKISTAN"},
    "QFA": {"name": "Qantas", "country": "Australia", "callsign": "QANTAS"},
    "QTR": {"name": "Qatar Airways", "country": "Qatar", "callsign": "QATARI"},
    "RAM": {"name": "Royal Air Maroc", "country": "Morocco", "callsign": "ROYAL AIR MAROC"},
    "RJA": {"name": "Royal Jordanian", "country": "Jordan", "callsign": "JORDANIAN"},
    "ROT": {"name": "TAROM", "country": "Romania", "callsign": "TAROM"},
    "RYR": {"name": "Ryanair", "country": "Ireland", "callsign": "RYANAIR"},
    "RZO": {"name": "SATA Air Acores", "country": "Portugal", "callsign": "SATA"},
    "SAA": {"name": "South African Airways", "country": "South Africa", "callsign": "SPRINGBOK"},
    "SAS": {"name": "Scandinavian Airlines", "country": "Sweden", "callsign": "SCANDINAVIAN"},
    "SAW": {"name": "Swiss Global Air Lines", "country": "Switzerland", "callsign": ""},
    "SDM": {"name": "Rossiya Airlines", "country": "Russia", "callsign": "RUSSIA"},
    "SEW": {"name": "Sky Express", "country": "Greece", "callsign": "SKY EXPRESS"},
    "SIA": {"name": "Singapore Airlines", "country": "Singapore", "callsign": "SINGAPORE"},
    "SKW": {"name": "SkyWest Airlines", "country": "United States", "callsign": "SKYWEST"},
    "SLK": {"name": "Silk Way Airlines", "country": "Azerbaijan", "callsign": "SILK LINE"},
    "SOU": {"name": "Southern Air", "country": "United States", "callsign": "SOUTHERN AIR"},
    "SVA": {"name": "Saudi Arabian Airlines", "country": "Saudi Arabia", "callsign": "SAUDIA"},
    "SWR": {"name": "Swiss Int'l Air Lines", "country": "Switzerland", "callsign": "SWISS"},
    "TAP": {"name": "TAP Air Portugal", "country": "Portugal", "callsign": "AIR PORTUGAL"},
    "TAR": {"name": "Tunisair", "country": "Tunisia", "callsign": "TUNAIR"},
    "THA": {"name": "Thai Airways", "country": "Thailand", "callsign": "THAI"},
    "THY": {"name": "Turkish Airlines", "country": "Turkey", "callsign": "TURKISH"},
    "TRA": {"name": "Transavia", "country": "Netherlands", "callsign": "TRANSAVIA"},
    "TVF": {"name": "Transavia France", "country": "France", "callsign": "FRANCE SOLEIL"},
    "TVS": {"name": "Travel Service", "country": "Czech Republic", "callsign": "SKYTRAVEL"},
    "UAE": {"name": "Emirates", "country": "United Arab Emirates", "callsign": "EMIRATES"},
    "UAL": {"name": "United Airlines", "country": "United States", "callsign": "UNITED"},
    "UPS": {"name": "UPS Airlines", "country": "United States", "callsign": "UPS"},
    "USA": {"name": "US Airways", "country": "United States", "callsign": "CACTUS"},
    "VIR": {"name": "Virgin Atlantic", "country": "United Kingdom", "callsign": "VIRGIN"},
    "VLG": {"name": "Vueling", "country": "Spain", "callsign": "VUELING"},
    "VOZ": {"name": "Virgin Australia", "country": "Australia", "callsign": "VELOCITY"},
    "VRD": {"name": "Virgin America", "country": "United States", "callsign": "REDWOOD"},
    "WJA": {"name": "WestJet", "country": "Canada", "callsign": "WESTJET"},
    "WZZ": {"name": "Wizz Air", "country": "Hungary", "callsign": "WIZZAIR"},
    "CTM": {"name": "Cotam (French Air Force)", "country": "France", "callsign": "COTAM"},
    "FAF": {"name": "French Air Force", "country": "France", "callsign": "FRENCH AIR FORCE"},
    "FNY": {"name": "French Navy", "country": "France", "callsign": "FRENCH NAVY"},
    "RCH": {"name": "US Air Force (AMC)", "country": "United States", "callsign": "REACH"},
    "RFF": {"name": "Securite Civile", "country": "France", "callsign": "DRAGON"},
    "RRR": {"name": "Royal Air Force", "country": "United Kingdom", "callsign": "ASCOT"},
    "NAF": {"name": "NATO/NAEW", "country": "International", "callsign": "NATO"},
    "CNV": {"name": "French Customs", "country": "France", "callsign": "FRENCH CUSTOMS"},
    "SXS": {"name": "SunExpress", "country": "Turkey", "callsign": "SUNEXPRESS"},
    "AHY": {"name": "Azerbaijan Airlines", "country": "Azerbaijan", "callsign": "AZAL"},
    "CAI": {"name": "Corendon Airlines", "country": "Turkey", "callsign": "CORENDON"},
    "ENT": {"name": "Enter Air", "country": "Poland", "callsign": "ENTER AIR"},
    "FHY": {"name": "Freebird Airlines", "country": "Turkey", "callsign": "FREEBIRD"},
    "MAC": {"name": "Air Arabia Maroc", "country": "Morocco", "callsign": "ARAB MAROC"},
    "ABR": {"name": "ASL Airlines Ireland", "country": "Ireland", "callsign": "CONTRACT"},
    "BCS": {"name": "European Air Transport", "country": "Belgium", "callsign": "EUROTRANS"},
    "BOX": {"name": "AeroLogic", "country": "Germany", "callsign": "GERMAN CARGO"},
    "CLX": {"name": "Cargolux", "country": "Luxembourg", "callsign": "CARGOLUX"},
    "CKS": {"name": "Kalitta Air", "country": "United States", "callsign": "CONNIE"},
    "MPH": {"name": "Martinair Cargo", "country": "Netherlands", "callsign": "MARTINAIR"},
    "NPT": {"name": "West Atlantic Sweden", "country": "Sweden", "callsign": "NEPTUNE"},
    "QYD": {"name": "Volotea", "country": "Spain", "callsign": "VOLOTEA"},
    "BZH": {"name": "Brit Air / HOP!", "country": "France", "callsign": "BRITAIR"},
    "HOP": {"name": "HOP!", "country": "France", "callsign": "AIR HOP"},
    "RLA": {"name": "Airlinair / HOP!", "country": "France", "callsign": "AIRLINAIR"},
    "CCM": {"name": "Air Corsica", "country": "France", "callsign": "CORSICA"},
    "VOE": {"name": "Volotea", "country": "Spain", "callsign": "VOLOTEA"},
    "AJT": {"name": "Amerijet International", "country": "United States", "callsign": "AMERIJET"},
    "THT": {"name": "Air Tahiti Nui", "country": "France", "callsign": "TAHITI"},
    "AJA": {"name": "Air Algerie", "country": "Algeria", "callsign": "AIR ALGERIE"},
    "DAH": {"name": "Air Algerie", "country": "Algeria", "callsign": "AIR ALGERIE"},
    "TSC": {"name": "Air Transat", "country": "Canada", "callsign": "AIR TRANSAT"},
    "AMC": {"name": "Air Malta", "country": "Malta", "callsign": "AIR MALTA"},
    "BIE": {"name": "Air Mediterranee", "country": "France", "callsign": "MEDITERRANEE"},
    "SWN": {"name": "Sundair", "country": "Germany", "callsign": "SUNDAIR"},
    "TUI": {"name": "TUI fly", "country": "Belgium", "callsign": "BEAUTY"},
    "TOM": {"name": "TUI Airways", "country": "United Kingdom", "callsign": "TOMJET"},
    "JAF": {"name": "TUI fly Nordic", "country": "Sweden", "callsign": "JETAIRFLY"},
    "OHY": {"name": "Onur Air", "country": "Turkey", "callsign": "ONUR AIR"},
    "AXM": {"name": "AirAsia", "country": "Malaysia", "callsign": "RED CAP"},
    "BGA": {"name": "Airbus Transport Int'l", "country": "France", "callsign": "BELUGA"},
    "JST": {"name": "Jetstar Airways", "country": "Australia", "callsign": "JETSTAR"},
    "NOS": {"name": "Neos", "country": "Italy", "callsign": "MOONFLOWER"},
    "SBI": {"name": "S7 Airlines", "country": "Russia", "callsign": "SIBERIAN"},
    "SJY": {"name": "Sriwijaya Air", "country": "Indonesia", "callsign": "SRIWIJAYA"},
    "SKV": {"name": "SkyGreece Airlines", "country": "Greece", "callsign": "SKYGREECE"},
    "TAM": {"name": "LATAM Brazil", "country": "Brazil", "callsign": "TAM"},
    "TFL": {"name": "Arkefly", "country": "Netherlands", "callsign": "ARKEFLY"},
    "ZZZ": {"name": "Unknown", "country": "", "callsign": ""},
}

AIRPORTS = {
    "EGLL": {"name": "Heathrow", "city": "London", "country": "United Kingdom", "iata": "LHR"},
    "EGLC": {"name": "London City", "city": "London", "country": "United Kingdom", "iata": "LCY"},
    "EGKK": {"name": "Gatwick", "city": "London", "country": "United Kingdom", "iata": "LGW"},
    "EGSS": {"name": "Stansted", "city": "London", "country": "United Kingdom", "iata": "STN"},
    "EHAM": {"name": "Schiphol", "city": "Amsterdam", "country": "Netherlands", "iata": "AMS"},
    "EDDF": {"name": "Frankfurt", "city": "Frankfurt", "country": "Germany", "iata": "FRA"},
    "EDDM": {"name": "Munich", "city": "Munich", "country": "Germany", "iata": "MUC"},
    "EDDB": {"name": "Berlin Brandenburg", "city": "Berlin", "country": "Germany", "iata": "BER"},
    "EDDL": {"name": "Dusseldorf", "city": "Dusseldorf", "country": "Germany", "iata": "DUS"},
    "EDDK": {"name": "Cologne Bonn", "city": "Cologne", "country": "Germany", "iata": "CGN"},
    "EDDH": {"name": "Hamburg", "city": "Hamburg", "country": "Germany", "iata": "HAM"},
    "EDDS": {"name": "Stuttgart", "city": "Stuttgart", "country": "Germany", "iata": "STR"},
    "LFPG": {"name": "Charles de Gaulle", "city": "Paris", "country": "France", "iata": "CDG"},
    "LFPO": {"name": "Orly", "city": "Paris", "country": "France", "iata": "ORY"},
    "LFBO": {"name": "Blagnac", "city": "Toulouse", "country": "France", "iata": "TLS"},
    "LFML": {"name": "Provence", "city": "Marseille", "country": "France", "iata": "MRS"},
    "LFLL": {"name": "Saint-Exupery", "city": "Lyon", "country": "France", "iata": "LYS"},
    "LFMN": {"name": "Cote d'Azur", "city": "Nice", "country": "France", "iata": "NCE"},
    "LFBD": {"name": "Merignac", "city": "Bordeaux", "country": "France", "iata": "BOD"},
    "LFRS": {"name": "Atlantique", "city": "Nantes", "country": "France", "iata": "NTE"},
    "LFRB": {"name": "Bretagne", "city": "Brest", "country": "France", "iata": "BES"},
    "LFST": {"name": "Entzheim", "city": "Strasbourg", "country": "France", "iata": "SXB"},
    "LFRN": {"name": "Saint-Jacques", "city": "Rennes", "country": "France", "iata": "RNS"},
    "LFPB": {"name": "Le Bourget", "city": "Paris", "country": "France", "iata": "LBG"},
    "LFBT": {"name": "Pyrenees", "city": "Tarbes/Lourdes", "country": "France", "iata": "LDE"},
    "LIRF": {"name": "Fiumicino", "city": "Rome", "country": "Italy", "iata": "FCO"},
    "LIMC": {"name": "Malpensa", "city": "Milan", "country": "Italy", "iata": "MXP"},
    "LIME": {"name": "Orio al Serio", "city": "Milan/Bergamo", "country": "Italy", "iata": "BGY"},
    "LIPZ": {"name": "Marco Polo", "city": "Venice", "country": "Italy", "iata": "VCE"},
    "LEMD": {"name": "Barajas", "city": "Madrid", "country": "Spain", "iata": "MAD"},
    "LEBL": {"name": "El Prat", "city": "Barcelona", "country": "Spain", "iata": "BCN"},
    "LEPA": {"name": "Son Sant Joan", "city": "Palma de Mallorca", "country": "Spain", "iata": "PMI"},
    "LEMG": {"name": "Costa del Sol", "city": "Malaga", "country": "Spain", "iata": "AGP"},
    "LPPT": {"name": "Portela", "city": "Lisbon", "country": "Portugal", "iata": "LIS"},
    "LPFR": {"name": "Faro", "city": "Faro", "country": "Portugal", "iata": "FAO"},
    "LSGG": {"name": "Cointrin", "city": "Geneva", "country": "Switzerland", "iata": "GVA"},
    "LSZH": {"name": "Zurich", "city": "Zurich", "country": "Switzerland", "iata": "ZRH"},
    "LSZA": {"name": "Agno", "city": "Lugano", "country": "Switzerland", "iata": "LUG"},
    "EBBR": {"name": "Zaventem", "city": "Brussels", "country": "Belgium", "iata": "BRU"},
    "ELLX": {"name": "Findel", "city": "Luxembourg", "country": "Luxembourg", "iata": "LUX"},
    "LOWW": {"name": "Schwechat", "city": "Vienna", "country": "Austria", "iata": "VIE"},
    "LOWI": {"name": "Innsbruck", "city": "Innsbruck", "country": "Austria", "iata": "INN"},
    "EKCH": {"name": "Kastrup", "city": "Copenhagen", "country": "Denmark", "iata": "CPH"},
    "ENGM": {"name": "Gardermoen", "city": "Oslo", "country": "Norway", "iata": "OSL"},
    "ESSA": {"name": "Arlanda", "city": "Stockholm", "country": "Sweden", "iata": "ARN"},
    "EFHK": {"name": "Vantaa", "city": "Helsinki", "country": "Finland", "iata": "HEL"},
    "EPWA": {"name": "Chopin", "city": "Warsaw", "country": "Poland", "iata": "WAW"},
    "LKPR": {"name": "Vaclav Havel", "city": "Prague", "country": "Czech Republic", "iata": "PRG"},
    "LHBP": {"name": "Liszt Ferenc", "city": "Budapest", "country": "Hungary", "iata": "BUD"},
    "LROP": {"name": "Henri Coanda", "city": "Bucharest", "country": "Romania", "iata": "OTP"},
    "LGAV": {"name": "Eleftherios Venizelos", "city": "Athens", "country": "Greece", "iata": "ATH"},
    "LTFM": {"name": "Istanbul", "city": "Istanbul", "country": "Turkey", "iata": "IST"},
    "LTAI": {"name": "Antalya", "city": "Antalya", "country": "Turkey", "iata": "AYT"},
    "UUEE": {"name": "Sheremetyevo", "city": "Moscow", "country": "Russia", "iata": "SVO"},
    "UUDD": {"name": "Domodedovo", "city": "Moscow", "country": "Russia", "iata": "DME"},
    "KJFK": {"name": "John F. Kennedy", "city": "New York", "country": "United States", "iata": "JFK"},
    "KLAX": {"name": "Los Angeles Int'l", "city": "Los Angeles", "country": "United States", "iata": "LAX"},
    "KORD": {"name": "O'Hare", "city": "Chicago", "country": "United States", "iata": "ORD"},
    "KATL": {"name": "Hartsfield-Jackson", "city": "Atlanta", "country": "United States", "iata": "ATL"},
    "KDFW": {"name": "Dallas/Fort Worth", "city": "Dallas", "country": "United States", "iata": "DFW"},
    "KSFO": {"name": "San Francisco Int'l", "city": "San Francisco", "country": "United States", "iata": "SFO"},
    "KMIA": {"name": "Miami Int'l", "city": "Miami", "country": "United States", "iata": "MIA"},
    "KBOS": {"name": "Logan", "city": "Boston", "country": "United States", "iata": "BOS"},
    "KEWR": {"name": "Newark Liberty", "city": "Newark", "country": "United States", "iata": "EWR"},
    "KDEN": {"name": "Denver Int'l", "city": "Denver", "country": "United States", "iata": "DEN"},
    "KSEA": {"name": "Seattle-Tacoma", "city": "Seattle", "country": "United States", "iata": "SEA"},
    "CYYZ": {"name": "Pearson", "city": "Toronto", "country": "Canada", "iata": "YYZ"},
    "CYUL": {"name": "Trudeau", "city": "Montreal", "country": "Canada", "iata": "YUL"},
    "CYVR": {"name": "Vancouver Int'l", "city": "Vancouver", "country": "Canada", "iata": "YVR"},
    "VHHH": {"name": "Hong Kong Int'l", "city": "Hong Kong", "country": "Hong Kong", "iata": "HKG"},
    "WSSS": {"name": "Changi", "city": "Singapore", "country": "Singapore", "iata": "SIN"},
    "RJTT": {"name": "Haneda", "city": "Tokyo", "country": "Japan", "iata": "HND"},
    "RJAA": {"name": "Narita", "city": "Tokyo", "country": "Japan", "iata": "NRT"},
    "RKSI": {"name": "Incheon", "city": "Seoul", "country": "South Korea", "iata": "ICN"},
    "ZBAA": {"name": "Capital Int'l", "city": "Beijing", "country": "China", "iata": "PEK"},
    "ZSPD": {"name": "Pudong", "city": "Shanghai", "country": "China", "iata": "PVG"},
    "VTBS": {"name": "Suvarnabhumi", "city": "Bangkok", "country": "Thailand", "iata": "BKK"},
    "OMDB": {"name": "Dubai Int'l", "city": "Dubai", "country": "United Arab Emirates", "iata": "DXB"},
    "OEJN": {"name": "King Abdulaziz", "city": "Jeddah", "country": "Saudi Arabia", "iata": "JED"},
    "OTHH": {"name": "Hamad Int'l", "city": "Doha", "country": "Qatar", "iata": "DOH"},
    "HECA": {"name": "Cairo Int'l", "city": "Cairo", "country": "Egypt", "iata": "CAI"},
    "GMMN": {"name": "Mohammed V", "city": "Casablanca", "country": "Morocco", "iata": "CMN"},
    "DTTA": {"name": "Tunis-Carthage", "city": "Tunis", "country": "Tunisia", "iata": "TUN"},
    "DAAG": {"name": "Houari Boumediene", "city": "Algiers", "country": "Algeria", "iata": "ALG"},
    "FAOR": {"name": "O.R. Tambo", "city": "Johannesburg", "country": "South Africa", "iata": "JNB"},
    "HAAB": {"name": "Bole Int'l", "city": "Addis Ababa", "country": "Ethiopia", "iata": "ADD"},
    "SBGR": {"name": "Guarulhos", "city": "Sao Paulo", "country": "Brazil", "iata": "GRU"},
    "SAEZ": {"name": "Ezeiza", "city": "Buenos Aires", "country": "Argentina", "iata": "EZE"},
    "MMMX": {"name": "Benito Juarez", "city": "Mexico City", "country": "Mexico", "iata": "MEX"},
    "YSSY": {"name": "Kingsford Smith", "city": "Sydney", "country": "Australia", "iata": "SYD"},
    "YMML": {"name": "Tullamarine", "city": "Melbourne", "country": "Australia", "iata": "MEL"},
    "NZAA": {"name": "Auckland", "city": "Auckland", "country": "New Zealand", "iata": "AKL"},
    "BIKF": {"name": "Keflavik", "city": "Reykjavik", "country": "Iceland", "iata": "KEF"},
    "EIDW": {"name": "Dublin", "city": "Dublin", "country": "Ireland", "iata": "DUB"},
    "EGCC": {"name": "Manchester", "city": "Manchester", "country": "United Kingdom", "iata": "MAN"},
    "EGPH": {"name": "Edinburgh", "city": "Edinburgh", "country": "United Kingdom", "iata": "EDI"},
    "EGBB": {"name": "Birmingham", "city": "Birmingham", "country": "United Kingdom", "iata": "BHX"},
    "VIDP": {"name": "Indira Gandhi", "city": "New Delhi", "country": "India", "iata": "DEL"},
    "VABB": {"name": "Chhatrapati Shivaji", "city": "Mumbai", "country": "India", "iata": "BOM"},
    "WIII": {"name": "Soekarno-Hatta", "city": "Jakarta", "country": "Indonesia", "iata": "CGK"},
    "WMKK": {"name": "Kuala Lumpur Int'l", "city": "Kuala Lumpur", "country": "Malaysia", "iata": "KUL"},
    "RPLL": {"name": "Ninoy Aquino", "city": "Manila", "country": "Philippines", "iata": "MNL"},
    "GCTS": {"name": "Tenerife South", "city": "Tenerife", "country": "Spain", "iata": "TFS"},
    "GCFV": {"name": "Fuerteventura", "city": "Fuerteventura", "country": "Spain", "iata": "FUE"},
    "GCLP": {"name": "Gran Canaria", "city": "Gran Canaria", "country": "Spain", "iata": "LPA"},
    "LDZA": {"name": "Franjo Tudman", "city": "Zagreb", "country": "Croatia", "iata": "ZAG"},
    "LDDU": {"name": "Dubrovnik", "city": "Dubrovnik", "country": "Croatia", "iata": "DBV"},
    "LJLJ": {"name": "Joze Pucnik", "city": "Ljubljana", "country": "Slovenia", "iata": "LJU"},
    "LYBE": {"name": "Nikola Tesla", "city": "Belgrade", "country": "Serbia", "iata": "BEG"},
    "LBSF": {"name": "Sofia", "city": "Sofia", "country": "Bulgaria", "iata": "SOF"},
    "LWSK": {"name": "Skopje", "city": "Skopje", "country": "North Macedonia", "iata": "SKP"},
    "LATN": {"name": "Tirana", "city": "Tirana", "country": "Albania", "iata": "TIA"},
    "LLBG": {"name": "Ben Gurion", "city": "Tel Aviv", "country": "Israel", "iata": "TLV"},
    "OLBA": {"name": "Beirut", "city": "Beirut", "country": "Lebanon", "iata": "BEY"},
    "OERK": {"name": "King Khalid", "city": "Riyadh", "country": "Saudi Arabia", "iata": "RUH"},
    "OBBI": {"name": "Bahrain Int'l", "city": "Bahrain", "country": "Bahrain", "iata": "BAH"},
    "OKBK": {"name": "Kuwait Int'l", "city": "Kuwait City", "country": "Kuwait", "iata": "KWI"},
    "OMAA": {"name": "Abu Dhabi", "city": "Abu Dhabi", "country": "United Arab Emirates", "iata": "AUH"},
    "OOMS": {"name": "Muscat Int'l", "city": "Muscat", "country": "Oman", "iata": "MCT"},
    "LFKJ": {"name": "Napoleon Bonaparte", "city": "Ajaccio", "country": "France", "iata": "AJA"},
    "LFKB": {"name": "Poretta", "city": "Bastia", "country": "France", "iata": "BIA"},
    "LFTH": {"name": "Toulon-Hyeres", "city": "Toulon", "country": "France", "iata": "TLN"},
    "LFMP": {"name": "Rivesaltes", "city": "Perpignan", "country": "France", "iata": "PGF"},
    "LFMT": {"name": "Mediterranee", "city": "Montpellier", "country": "France", "iata": "MPL"},
    "LFLB": {"name": "Chambery", "city": "Chambery", "country": "France", "iata": "CMF"},
    "LFLC": {"name": "Aulnat", "city": "Clermont-Ferrand", "country": "France", "iata": "CFE"},
    "LFBZ": {"name": "Anglet", "city": "Biarritz", "country": "France", "iata": "BIQ"},
    "LFRQ": {"name": "Pluguffan", "city": "Quimper", "country": "France", "iata": "UIP"},
    "LFLP": {"name": "Meythet", "city": "Annecy", "country": "France", "iata": "NCY"},
    "LFLS": {"name": "Saint-Geoirs", "city": "Grenoble", "country": "France", "iata": "GNB"},
    "LFTW": {"name": "Garons", "city": "Nimes", "country": "France", "iata": "FNI"},
    "LFRH": {"name": "Lann-Bihoue", "city": "Lorient", "country": "France", "iata": "LRT"},
    "LFOT": {"name": "Val de Loire", "city": "Tours", "country": "France", "iata": "TUF"},
    "LFPN": {"name": "Toussus-le-Noble", "city": "Paris", "country": "France", "iata": "TNF"},
    "LFPT": {"name": "Pontoise", "city": "Paris", "country": "France", "iata": "POX"},
}


def main():
    os.makedirs(DATA_DIR, exist_ok=True)

    airlines_path = os.path.join(DATA_DIR, "airlines.json")
    with open(airlines_path, "w") as f:
        json.dump(AIRLINES, f, separators=(",", ":"))
    print(f"Airlines: {len(AIRLINES)} entries -> {airlines_path}")

    airports_path = os.path.join(DATA_DIR, "airports.json")
    with open(airports_path, "w") as f:
        json.dump(AIRPORTS, f, separators=(",", ":"))
    print(f"Airports: {len(AIRPORTS)} entries -> {airports_path}")


if __name__ == "__main__":
    main()
